# Custom Language File for Launcher Customizer

[ejs.app]
title = "Alduin Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/norwen78/alduinrp"
mediaXURL = "#"
mediaInstagramURL = "https://www.instagram.com/alduinrp/"
mediaYouTubeURL = "https://www.youtube.com/watch?v=mSWQ6YytqMg"
mediaDiscordURL = "https://discord.com/invite/a8VDYaJUZx"

[ejs.settings]
sourceGithubLink = "https://github.com/norwen78/alduinrp"
supportLink = "https://github.com/norwen78/alduinrp/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Alduin"
welcomeDescription = "AlduinRP est un serveur Serious RP.   Incarnez qui vous souhaitez au bas de l'échelle sociale et gravissez là si c'est votre but ou vivez votre vie paisible même si nul nest a l'abri.    Alduin vous offre la possibilité de ressentir une expérience médiévale qui cherche de jours en jours a atteindre un réalisme et une proximité toujours plus grande."
welcomeDescCTA = "Tu n’es qu’à quelques clics de nous rejoindre."
